### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by RiuKy** [Previews-app/Previews-WebmToMp4#2]
When I convert the webm video to the mp4 one it converts without audio

**Comment by Previews-app** [comment]
this project uses the ffmpeg, this seems like an issue with ffmpeg and your system, to further diagnose the issue you would need to open an issue with the creators of ffmpeg.

**Comment by Previews-app** [comment]
issue found and fixed, apparently there was no audio in editing softwares. you can download the new project and it should work.
